### ISSUE TITLE
Unable to attempt to run crash script

### ISSUE THREAD

**Issue by nonetrix** [geohot/7900xtx#1]
I was attempting to test this script to see if it would trigger similar issue I am having on my RX 6800, however it seems I am getting the following error when attempting to run it
```
Traceback (most recent call last):
  File "/home/noah/Documents/AI/7900xtx/crash/driver.py", line 43, in <module>
    kio = ioctls_from_header()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/Documents/AI/7900xtx/crash/driver.py", line 41, in ioctls_from_header
    fxns[name.replace("AMDKFD_IOC_", "").lower()] = functools.partial(kfd_ioctl, idirs[idir], int(nr, 0x10), getattr(kfd, "struct_"+sname))
                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'kfd' has no attribute 'struct_kfd_ioctl_criu_args'. Did you mean: 'struct_kfd_ioctl_svm_args'?
```
Seems to be a issue in the kfd.py script itself and not really related to me running a older card to anything like that, however, I don't really understand the low level code enough to say for sure exactly

**Comment by geohot** [comment]
It's probably because you have a different version of that header file it opens. You don't need that function, should be able to try except it.

**Comment by nonetrix** [comment]
Will try that and post results I guess

**Comment by nonetrix** [comment]
Not able to get it to run still keep running into errors I give up for now, if anyone else wants to try getting it to run on older cards they can try I guess so I guess I can keep the issue open. The code is way above my knowledge level unfortunately lol
